export const SBS_REGISTERS = [
  { addr: 0x08, name: "Temperature", unit: "°C", scale: 0.1, offset: -273.15, desc: "Pack Temperature" },
  { addr: 0x09, name: "Voltage", unit: "mV", scale: 1, desc: "Pack Total Voltage" },
  { addr: 0x0A, name: "Current", unit: "mA", scale: 1, signed: true, desc: "Pack Current (+ Charge, - Discharge)" },
  { addr: 0x0B, name: "AverageCurrent", unit: "mA", scale: 1, signed: true, desc: "Rolling Average Pack Current" },
  { addr: 0x0D, name: "RelativeStateOfCharge", unit: "%", scale: 1, desc: "State of Charge" },
  { addr: 0x0E, name: "AbsoluteStateOfCharge", unit: "%", scale: 1, desc: "Absolute SoC" },
  { addr: 0x0F, name: "RemainingCapacity", unit: "mAh", scale: 1, desc: "Remaining Capacity" },
  { addr: 0x10, name: "FullChargeCapacity", unit: "mAh", scale: 1, desc: "Full Charge Capacity" },
  { addr: 0x3C, name: "CellVoltage4", unit: "mV", scale: 1, desc: "Cell 4 Voltage" },
  { addr: 0x3D, name: "CellVoltage3", unit: "mV", scale: 1, desc: "Cell 3 Voltage" },
  { addr: 0x3E, name: "CellVoltage2", unit: "mV", scale: 1, desc: "Cell 2 Voltage" },
  { addr: 0x3F, name: "CellVoltage1", unit: "mV", scale: 1, desc: "Cell 1 Voltage" },
  { addr: 0x51, name: "SafetyStatus", unit: "HEX", scale: 1, isBitfield: true, desc: "Safety Protection Status Flags" },
  { addr: 0x54, name: "OperationStatus", unit: "HEX", scale: 1, isBitfield: true, desc: "System & FET Operating Status Flags" },
];

// BQ40Z50-R1 TRM SLUUBC1D, sections 13.1.37 and 13.1.40.
export const SAFETY_STATUS_FLAGS = [
  { bit: 0, code: "CUV", label: "Cell Undervoltage", severity: "danger", desc: "Cell Undervoltage protection is active" },
  { bit: 1, code: "COV", label: "Cell Overvoltage", severity: "danger", desc: "Cell Overvoltage protection is active" },
  { bit: 2, code: "OCC1", label: "Overcurrent Charge 1", severity: "danger", desc: "Overcurrent Charge 1 protection is active" },
  { bit: 3, code: "OCC2", label: "Overcurrent Charge 2", severity: "danger", desc: "Overcurrent Charge 2 protection is active" },
  { bit: 4, code: "OCD1", label: "Overcurrent Discharge 1", severity: "danger", desc: "Overcurrent Discharge 1 protection is active" },
  { bit: 5, code: "OCD2", label: "Overcurrent Discharge 2", severity: "danger", desc: "Overcurrent Discharge 2 protection is active" },
  { bit: 6, code: "AOLD", label: "Overload Discharge", severity: "danger", desc: "Overload Discharge protection is active" },
  { bit: 7, code: "AOLDL", label: "Overload Discharge Latch", severity: "danger", desc: "Overload Discharge Latch protection is active" },
  { bit: 8, code: "ASCC", label: "Short Circuit Charge", severity: "danger", desc: "Short Circuit Charge protection is active" },
  { bit: 9, code: "ASCCL", label: "Short Circuit Charge Latch", severity: "danger", desc: "Short Circuit Charge Latch protection is active" },
  { bit: 10, code: "ASCD", label: "Short Circuit Discharge", severity: "danger", desc: "Short Circuit Discharge protection is active" },
  { bit: 11, code: "ASCDL", label: "Short Circuit Discharge Latch", severity: "danger", desc: "Short Circuit Discharge Latch protection is active" },
  { bit: 12, code: "OTC", label: "Overtemperature Charge", severity: "danger", desc: "Overtemperature Charge protection is active" },
  { bit: 13, code: "OTD", label: "Overtemperature Discharge", severity: "danger", desc: "Overtemperature Discharge protection is active" },
  { bit: 14, code: "CUVC", label: "Compensated Cell Undervoltage", severity: "danger", desc: "Compensated Cell Undervoltage protection is active" },
  { bit: 16, code: "OTF", label: "FET Overtemperature", severity: "danger", desc: "FET Overtemperature protection is active" },
  { bit: 18, code: "PTO", label: "Precharge Timeout", severity: "danger", desc: "Precharge Timeout protection is active" },
  { bit: 20, code: "CTO", label: "Charge Timeout", severity: "danger", desc: "Charge Timeout protection is active" },
  { bit: 22, code: "OC", label: "Overcharge", severity: "danger", desc: "Overcharge protection is active" },
  { bit: 23, code: "CHGC", label: "Overcharging Current", severity: "danger", desc: "Overcharging Current protection is active" },
  { bit: 24, code: "CHGV", label: "Overcharging Voltage", severity: "danger", desc: "Overcharging Voltage protection is active" },
  { bit: 25, code: "PCHGC", label: "Overprecharge Current", severity: "danger", desc: "Overprecharge Current protection is active" },
  { bit: 26, code: "UTC", label: "Undertemperature Charge", severity: "danger", desc: "Undertemperature Charge protection is active" },
  { bit: 27, code: "UTD", label: "Undertemperature Discharge", severity: "danger", desc: "Undertemperature Discharge protection is active" },
 ];

export const OPERATION_STATUS_FLAGS = [
  { bit: 0, code: "PRES", label: "System Present", severity: "info", desc: "System present status" },
  { bit: 1, code: "DSG", label: "Discharge FET ON", severity: "success", desc: "Discharge FET enabled" },
  { bit: 2, code: "CHG", label: "Charge FET ON", severity: "success", desc: "Charge FET enabled" },
  { bit: 3, code: "PCHG", label: "Precharge FET ON", severity: "info", desc: "Precharge FET enabled" },
  { bit: 5, code: "FUSE", label: "Fuse Status", severity: "danger", desc: "Fuse status active" },
  { bit: 11, code: "SS", label: "Safety Status", severity: "danger", desc: "Safety protection active" },
  { bit: 12, code: "PF", label: "Permanent Failure", severity: "danger", desc: "Permanent failure mode" },
  { bit: 13, code: "XDSG", label: "Discharging Disabled", severity: "warning", desc: "Discharging disabled" },
  { bit: 14, code: "XCHG", label: "Charging Disabled", severity: "warning", desc: "Charging disabled" },
  { bit: 15, code: "SLEEP", label: "Sleep Mode", severity: "info", desc: "Sleep conditions met" },
  { bit: 28, code: "CB", label: "Cell Balancing Active", severity: "info", desc: "Cell balancing active" },
];
